//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FierceStukCloud_PC {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class FSC_Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static FSC_Settings defaultInstance = ((FSC_Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FSC_Settings())));
        
        public static FSC_Settings Default {
            get {
                return defaultInstance;
            }
        }

        public string Login { get; internal set; }
        public string Password { get; internal set; }
    }
}
