//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using System.Security;

namespace FierceStukCloud_PC {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class FSC_Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static FSC_Settings defaultInstance = ((FSC_Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FSC_Settings())));
        
        public static FSC_Settings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Login
        {
            get
            {
                //this["Login"] = "";
                //Save();
                //var values = this["Login"];
                return ((string)(this["Login"]));
            }
            set
            {
                this["Login"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password
        {
            get
            {
                return ((string)(this["Login"]));
            }
            set
            {
                this["Login"] = value;
            }
        }
    }
}
