// <auto-generated />
using System;
using FierceStukCloud.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FierceStukCloud.EntityFramework.Migrations
{
    [DbContext(typeof(FierceStukCloudDbContext))]
    partial class FierceStukCloudDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FierceStukCloud.Core.Extension.SongPlayList", b =>
                {
                    b.Property<Guid>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Place")
                        .HasColumnType("int");

                    b.HasKey("SongId", "PlayListId");

                    b.HasIndex("PlayListId");

                    b.ToTable("SongPlayList");
                });

            modelBuilder.Entity("FierceStukCloud.Core.PlayList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnName("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUri")
                        .HasColumnName("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OnDevice")
                        .HasColumnName("OnDevice")
                        .HasColumnType("bit");

                    b.Property<bool>("OnServer")
                        .HasColumnName("OnServer")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnName("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLogin")
                        .HasColumnName("UserLogin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlayLists");
                });

            modelBuilder.Entity("FierceStukCloud.Core.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Album")
                        .HasColumnName("Album")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Author")
                        .HasColumnName("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .HasColumnName("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFavorite")
                        .HasColumnName("Favorite")
                        .HasColumnType("bit");

                    b.Property<string>("LocalUrl")
                        .HasColumnName("LocalUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OnDevice")
                        .HasColumnName("OnDevice")
                        .HasColumnType("bit");

                    b.Property<bool>("OnServer")
                        .HasColumnName("OnServer")
                        .HasColumnType("bit");

                    b.Property<string>("OptionalInfo")
                        .HasColumnName("OptionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnName("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLogin")
                        .HasColumnName("UserLogin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Year")
                        .HasColumnName("Year")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("FierceStukCloud.Core.Extension.SongPlayList", b =>
                {
                    b.HasOne("FierceStukCloud.Core.PlayList", "PlayList")
                        .WithMany("Songs")
                        .HasForeignKey("PlayListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FierceStukCloud.Core.Song", "Song")
                        .WithMany("PlayLists")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
